name: 'dbt_model_voice_ai'
version: '1.0.0'
profile: 'dbt_model_voice_ai_profile'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
models:
  dbt_model_voice_ai:
    example:
      +materialized: view
